name: Run php-cs-fixer

on:
  push:
    branches-ignore:
    - master

jobs:
  php-cs-fixer:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run php-cs-fixer
      run: |
        set -euo pipefail
        git fetch --no-tags --prune --depth=1 origin master
        vendor/bin/php-cs-fixer fix
        if git diff --exit-code; then
          git commit -am "Run php-cs-fixer"
          git push origin HEAD
        fi
