name: Run php-cs-fixer
on: [push]

jobs:
    php-cs-fixer:
        name: php-cs-fixer
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run php-cs-fixer
          run: |
            set -euo pipefail
            git diff --name-only origin/master | xargs -d'\n' -r vendor/bin/php-cs-fixer fix
            git diff --exit-code
