name: Run php-cs-fixer
on: [push]

jobs:
    php-cs-fixer:
        name: php-cs-fixer
        runs-on: ubuntu-latest
        steps:
        - name: Run php-cs-fixer
          run: vendor/bin/php-cs-fixer fix --format=json | jq -r '.files[]' | tee /tmp/fixed-files
        - name: Assert no files were fixed
          run: '[[ ! -s /tmp/fixed-files ]]'
